name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cripto-check:latest
        docker run -d -p 5000:5000 -e app_mode=test  cripto-check
        curl http://localhost:5000/EUR
        curl http://localhost:5000/GBP
        curl http://localhost:5000/ZZZ
