name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag cripto-check:latest
    - name: Run container in test mode
      run: |
        docker run -d -p 5000:5000 -e app_mode=test  cripto-check
        sleep 10
    - name: Run Unit Tests (Legit request)
      run: |
        echo "Running Legit request"
        curl http://localhost:5000/EUR
        echo "Test done"
    - name: Run Unit Tests (Wrong Json respose)
      run: |
        echo "Running Wrong Json respose"
        curl http://localhost:5000/GBP
        echo "Test done"
    - name: Run Unit Tests (Wrong Currency)
      run: |
        echo "Running Wrong Currency"
        curl http://localhost:5000/ZZZ
        echo "Test done"
